language: java
sudo: false
jdk: oraclejdk7
script: ./travis.sh

cache:
  directories:
    - $HOME/.m2/repository

notifications:
  email: false
  webhooks:
    - secure: "qvddRFjEzB+zQbekENWKzy15umf/r7uJcnd7Y898eZ6LvzNt7OfCiZQNc/HvJJHshEdepg0/1tjbf6N7mhs1AxsMUV8Yr6VB/s/ooTnqyoeJh1xQVCxbE4pKu4e52WaybySEH3hHIpFp0y1eMYjY647GeiPCFd5Wb9fE6Z9kVPk2Z9sUOBMiUUd76nUykOcNLWCG9MH/BvcZccWHF8+ItSl9ZkoeHcb7IsPbZc0yEFWY9AN85CPBJHO204RYdlkqWGTKnQ/Ht94WDEuerzOLVJNTFd14Bubo1FTHd2SPJDS42qitsUReIl9ZgBRKz0LNJcFW/c9TzUvYAJ1D+eYsYLmovrBQAA5DJv6X86m5cqw6tbT1tAcGXH+Q+j41w59055dKIXW7cUEbYnXZfjULrZfDpYAOIyI2Js/n24pfD5P8e6vt02v0IAUe+gnZP0o+R/3q2xtPCmbwK3ITAyKouxxbxpKJgm8UrM+5e8PyIc+w2eEAkj7n+BSQ6K0RwIfiwOnJGrd9rUHDmizQPgHeTDmm9+lYLG4ohCtalB8cMPINij7s/jB/+4m+vz10bBkmnDibqQcotaIRY5cpgwTPQmrede4MpX2wv6qv4KGRG+5y/0iwa9kzQ3/zlllo8A6r6CCSLVLzVVk4ruitrjPqHvhvszSiJ1il3vkxMbgIlJA="

